#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Type checking
npm run typecheck

# Run all tests
npm run test

# Verify build
npm run build

# Run lint-staged for formatting and specific file checks
npx lint-staged
